spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: xxx
    username: xxx
    password: xxx
  transaction:
    rollback-on-commit-failure: true
  profiles:
    active: dev
#  transaction:
#    rollback-on-commit-failure: true
server:
  tomcat:
    resource:
      allow-caching: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true

